title: Swift Note
description: Simple Swift code reference
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
author: Will Chiu
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
